[package]
name = "sgx_tstd"
version = "0.9.1"
authors = ["Baidu"]
build = "build.rs"

[features]
default = ["backtrace"]
global_exit = []
backtrace = ["stdio"]
stdio = []

[build-dependencies]
build_helper = { path = "../build_helper" }

[dependencies]
sgx_types = { path = "../sgx_types" }
sgx_trts = { path = "../sgx_trts" }
sgx_alloc = { path = "../sgx_alloc" }
sgx_tprotected_fs = { path = "../sgx_tprotected_fs" }

[dependencies.libc]
git = "https://github.com/rust-lang/libc"
